import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";

import "@/globals.css";

const dmSans = DM_Sans({
  weight: ["400", "500"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "UpScale Reputation System",
  description: "Generated by create next app",
};

export default function HomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${dmSans.className} bg-black text-white antialiased`}>
        {children}
      </body>
    </html>
  );
}
